# fly.toml app configuration file generated for vite-react-ppt on 2024-12-19T14:30:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "vite-react-ppt"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
